import React from 'react';
import getRecipes from '../actions/getRecipes';
import Link from 'next/link';
import Image from 'next/image';

export const revalidate = 3600;

export const metadata = {
  title: 'Discover authentic recipes and cooking inspiration | Smart Recipe AI',
  description:
    'Discover recipes from around the world. Find a selection of delicious recipes generated by AI and more.',
};

const FeaturedRecipes = async () => {
  const recipes = await getRecipes();

  return (
    <section>
      {/* Hero Section */}
      <div className='relative h-[500px] w-full'>
        {/* Background Image */}
        <Image
          src='/hero-image-two.jpg'
          alt='Cooking ingredients and utensils'
          fill
          className='object-cover'
          priority
        />
        {/* Overlay */}
        <div className='absolute inset-0 bg-primary/95' />
        {/* Content */}
        <div className='relative h-full flex items-center justify-center'>
          <div className='text-center max-w-3xl px-6'>
            <h1 className='text-4xl md:text-5xl font-bold mb-4'>
              Welcome to the Smart RecipeBlog
            </h1>
            <h2 className='text-lg md:text-xl'>
              Discover authentic recipes, cooking inspiration and more, all in
              one place.
            </h2>
          </div>
        </div>
      </div>

      {/* Recipes Grid */}
      <div className='relative space-y-6 container mx-auto py-20 px-6'>
        <div className='flex flex-col'>
          <div className='flex flex-wrap justify-center items-center flex-row gap-8'>
            {recipes.map((recipe, index) => (
              <div
                key={`recipe-${index}`}
                className='card bg-base-100 shadow-xl cursor-pointer hover:shadow-2xl transition-shadow max-w-[400px]'
              >
                <Link href={`/blog/${recipe.slug}`}>
                  <div className='card-body'>
                    <h2 className='card-title'>
                      {recipe.title || recipe.name}
                    </h2>
                    <p className='mb-2'>
                      {recipe.description?.replace(/<[^>]+>/g, '').slice(0, 80)}
                      {recipe.description && recipe.description.replace(/<[^>]+>/g, '').length > 80 && '...'}
                    </p>
                    <div className='origin-center w-fit'>
                      <p className='text-secondary mb-4 px-2 py-2 bg-gray-100 rounded-xl'>
                        {new Date(recipe.created).toLocaleDateString('en-GB', {
                          day: 'numeric',
                          month: 'long',
                          year: 'numeric',
                        })}
                      </p>
                      <Link
                        href={`/blog/${recipe.slug}`}
                        className='mt-6 text-primary/90 hover:text-primary/70 font-bold'
                      >
                        View Post →
                      </Link>
                    </div>
                  </div>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default FeaturedRecipes;
