import React from 'react';
import getRecipes from '../actions/getRecipes';
import Link from 'next/link';
import Image from 'next/image';

export const revalidate = 3600;

export const metadata = {
  title: 'Discover authentic recipes and cooking inspiration | SmartRecipe AI',
  description:
    'Discover recipes from around the world. Find a selection of delicious recipes generated by AI and more.',
};

const FeaturedRecipes = async () => {
  const recipes = await getRecipes();

  return (
    <section>
      {/* Hero Section */}
      <div className='relative h-[400px] w-full'>
        {/* Background Image */}
        <Image
          src='/hero-image-two.jpg'
          alt='Cooking ingredients and utensils'
          fill
          className='object-cover'
          priority
        />
        {/* Overlay */}
        <div className='absolute inset-0 bg-black/60' />
        {/* Content */}
        <div className='relative h-full flex items-center justify-center'>
          <div className='text-center text-white max-w-3xl px-6'>
            <h1 className='text-4xl md:text-5xl font-bold mb-4'>
              Welcome to the SmartRecipe Blog
            </h1>
            <h2 className='text-lg md:text-xl text-white/90'>
              Discover authentic recipes, cooking inspiration and more, all in
              one place.
            </h2>
          </div>
        </div>
      </div>

      {/* Recipes Grid */}
      <div className='relative space-y-6 container mx-auto pb-20 pt-10 px-6'>
        <div className='flex flex-col gap-8'>
          <div className='flex flex-wrap flex-row gap-4'>
            {recipes.map((recipe, index) => (
              <div
                key={`recipe-${index}`}
                className='card bg-base-100 shadow-xl cursor-pointer hover:shadow-2xl transition-shadow max-w-[600px]'
              >
                <div className='card-body'>
                  <h2 className='card-title'>{recipe.title || recipe.name}</h2>
                  <p
                    className='mb-4'
                    dangerouslySetInnerHTML={{ __html: recipe.description }}
                  ></p>
                  <div className='flex gap-2 mt-2 mb-4'>
                    <div className='bg-gray-500/10 text-gray-500 rounded-lg p-2 w-fit text-sm'>
                      <p>{recipe.cookTime}</p>
                    </div>
                    <div className='bg-gray-500/10 text-gray-500 rounded-lg p-2 w-fit text-sm'>
                      <p>{recipe.difficulty}</p>
                    </div>
                  </div>
                  <div className='origin-center w-fit'>
                    <Link
                      href={`/blog/${recipe.slug}`}
                      className='mt-6 text-primary/90 hover:text-primary/70 font-bold'
                    >
                      View Recipe →
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default FeaturedRecipes;
