import React from 'react';

const Terms = () => {
  return (
    <section className='bg-white min-h-screen py-12 px-4 sm:px-6 lg:px-8'>
      <div className='max-w-4xl mx-auto'>
        <h1 className='text-4xl font-bold text-gray-900 mb-8'>
          Terms and Conditions
        </h1>

        <div className='space-y-8'>
          {/* Introduction */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              1. Introduction
            </h2>
            <p className='text-gray-600 leading-relaxed'>
              Welcome to SmartRecipe AI. These Terms and Conditions govern your
              use of our website smartrecipeai.com and our AI-powered recipe
              generation service. By accessing or using our service, you agree
              to be bound by these Terms.
            </p>
          </div>

          {/* Definitions */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              2. Definitions
            </h2>
            <ul className='list-disc list-inside text-gray-600 space-y-2'>
              <li>
                "Service" refers to the SmartRecipe AI website and recipe
                generation platform
              </li>
              <li>
                "User" refers to any individual or entity using our Service
              </li>
              <li>
                "Content" refers to recipes, text, images, and other materials
                generated by our Service
              </li>
              <li>
                "Account" refers to a registered user profile on our Service
              </li>
            </ul>
          </div>

          {/* Account Terms */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              3. Account Terms
            </h2>
            <ul className='list-disc list-inside text-gray-600 space-y-2'>
              <li>You must be at least 16 years old to use this Service</li>
              <li>
                You are responsible for maintaining the security of your account
              </li>
              <li>
                You must provide accurate and complete information when creating
                an account
              </li>
              <li>
                You are responsible for all activities that occur under your
                account
              </li>
              <li>
                We reserve the right to suspend or terminate accounts that
                violate these Terms
              </li>
            </ul>
          </div>

          {/* Service Usage */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              4. Service Usage
            </h2>
            <p className='text-gray-600 leading-relaxed mb-4'>
              Our Service provides AI-generated recipes based on user-selected
              ingredients. By using our Service, you agree to:
            </p>
            <ul className='list-disc list-inside text-gray-600 space-y-2'>
              <li>Use the Service only for lawful purposes</li>
              <li>Not attempt to reverse engineer or decompile the Service</li>
              <li>
                Not use the Service to generate harmful or inappropriate content
              </li>
              <li>Not use automated systems or bots to access the Service</li>
              <li>Not share your account credentials with others</li>
            </ul>
          </div>

          {/* Intellectual Property */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              5. Intellectual Property
            </h2>
            <p className='text-gray-600 leading-relaxed mb-4'>
              All content generated by our Service is provided for personal use
              only. You may:
            </p>
            <ul className='list-disc list-inside text-gray-600 space-y-2'>
              <li>Use generated recipes for personal cooking</li>
              <li>Share recipes with friends and family</li>
              <li>Save recipes to your personal collection</li>
            </ul>
            <p className='text-gray-600 leading-relaxed mt-4'>You may not:</p>
            <ul className='list-disc list-inside text-gray-600 space-y-2'>
              <li>
                Use our content for commercial purposes without permission
              </li>
              <li>Claim ownership of AI-generated recipes</li>
              <li>Resell or redistribute our content</li>
            </ul>
          </div>

          {/* Payment Terms */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              6. Payment Terms
            </h2>
            <ul className='list-disc list-inside text-gray-600 space-y-2'>
              <li>Free credits are provided upon registration</li>
              <li>Additional credits can be purchased through our platform</li>
              <li>
                All payments are processed securely through our payment
                providers
              </li>
              <li>Credits are non-refundable and non-transferable</li>
              <li>We reserve the right to modify our pricing with notice</li>
            </ul>
          </div>

          {/* Limitation of Liability */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              7. Limitation of Liability
            </h2>
            <p className='text-gray-600 leading-relaxed'>
              SmartRecipe AI is not responsible for:
            </p>
            <ul className='list-disc list-inside text-gray-600 mt-2 space-y-2'>
              <li>
                Any allergic reactions or health issues from following our
                recipes
              </li>
              <li>Accuracy of nutritional information</li>
              <li>Service interruptions or technical issues</li>
              <li>Loss of data or content</li>
              <li>Third-party actions or content</li>
            </ul>
          </div>

          {/* Disclaimer */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              8. Disclaimer
            </h2>
            <p className='text-gray-600 leading-relaxed'>
              Our Service is provided "as is" without any warranties. We do not
              guarantee:
            </p>
            <ul className='list-disc list-inside text-gray-600 mt-2 space-y-2'>
              <li>Uninterrupted or error-free service</li>
              <li>Accuracy of AI-generated recipes</li>
              <li>Compatibility with all devices or browsers</li>
              <li>Results from using our recipes</li>
            </ul>
          </div>

          {/* Modifications */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              9. Modifications to Terms
            </h2>
            <p className='text-gray-600 leading-relaxed'>
              We reserve the right to modify these Terms at any time. Users will
              be notified of significant changes. Continued use of the Service
              after changes constitutes acceptance of the new Terms.
            </p>
          </div>

          {/* Termination */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              10. Termination
            </h2>
            <p className='text-gray-600 leading-relaxed'>
              We may terminate or suspend your access to the Service:
            </p>
            <ul className='list-disc list-inside text-gray-600 mt-2 space-y-2'>
              <li>For violations of these Terms</li>
              <li>For fraudulent or illegal activity</li>
              <li>At our sole discretion</li>
            </ul>
          </div>

          {/* Governing Law */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              11. Governing Law
            </h2>
            <p className='text-gray-600 leading-relaxed'>
              These Terms are governed by the laws of [Your Jurisdiction]. Any
              disputes shall be resolved in the courts of [Your Jurisdiction].
            </p>
          </div>

          {/* Contact Information */}
          <div>
            <h2 className='text-2xl font-semibold text-gray-900 mb-4'>
              12. Contact Information
            </h2>
            <p className='text-gray-600 leading-relaxed'>
              For questions about these Terms, please contact us at:
            </p>
            <ul className='list-disc list-inside text-gray-600 mt-2 space-y-1'>
              <li>Email: help@smartrecipeai.com</li>
              <li>Website: smartrecipeai.com</li>
            </ul>
          </div>

          {/* Last Updated */}
          <div>
            <p className='text-gray-600 leading-relaxed'>
              Last updated: May 16, 2025
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Terms;
