export const ingredients = {
  Proteins: [
    { name: 'chicken breast', icon: '🍗' },
    { name: 'chicken thigh', icon: '🍗' },
    { name: 'minced beef', icon: '🥩' },
    { name: 'beef steak', icon: '🥩' },
    { name: 'pork sausages', icon: '🌭' },
    { name: 'bacon', icon: '🥓' },
    { name: 'gammon', icon: '🍖' },
    { name: 'pork belly', icon: '🍖' },
    { name: 'lamb chops', icon: '🍢' },
    { name: 'lamb shank', icon: '🍖' },
    { name: 'duck breast', icon: '🦆' },
    { name: 'rabbit', icon: '🐇' },
    { name: 'venison', icon: '🍖' },
    { name: 'cod', icon: '🐟' },
    { name: 'haddock', icon: '🐟' },
    { name: 'salmon', icon: '🐟' },
    { name: 'prawns', icon: '🦐' },
    { name: 'scampi', icon: '🦐' },
    { name: 'eggs', icon: '🥚' },
    { name: 'tofu', icon: '🍱' },
    { name: 'tempeh', icon: '🌱' },
    { name: 'halloumi', icon: '🧀' },
    { name: 'black pudding', icon: '🍖' },
  ],
  Vegetables: [
    { name: 'mushrooms', icon: '🍄' },
    { name: 'aubergine', icon: '🍆' },
    { name: 'broccoli', icon: '🥦' },
    { name: 'cauliflower', icon: '🥦' },
    { name: 'parsnips', icon: '🥕' },
    { name: 'courgette', icon: '🥒' },
    { name: 'cucumber', icon: '🥒' },
    { name: 'butternut squash', icon: '🎃' },
    { name: 'leeks', icon: '🥬' },
    { name: 'spinach', icon: '🥬' },
    { name: 'kale', icon: '🥬' },
    { name: 'cabbage', icon: '🥬' },
    { name: 'onion', icon: '🧅' },
    { name: 'spring onion', icon: '🧅' },
    { name: 'garlic', icon: '🧄' },
    { name: 'tomato', icon: '🍅' },
    { name: 'pepper', icon: '🫑' },
    { name: 'chilli', icon: '🌶️' },
    { name: 'carrot', icon: '🥕' },
    { name: 'sweetcorn', icon: '🌽' },
    { name: 'peas', icon: '🟢' },
    { name: 'leek', icon: '🧅' },
    { name: 'beetroot', icon: '🧃' },
    { name: 'brussels sprouts', icon: '🥬' },
    { name: 'watercress', icon: '🥬' },
    { name: 'lettuce', icon: '🥬' },
    { name: 'fennel', icon: '🌿' },
    { name: 'chard', icon: '🌿' },
  ],
  Fruits: [
    { name: 'apple', icon: '🍎' },
    { name: 'banana', icon: '🍌' },
    { name: 'orange', icon: '🍊' },
    { name: 'pineapple', icon: '🍍' },
    { name: 'lemon', icon: '🍋' },
    { name: 'lime', icon: '🍈' },
    { name: 'strawberries', icon: '🍓' },
    { name: 'blueberries', icon: '🫐' },
    { name: 'raspberries', icon: '🍓' },
    { name: 'blackberries', icon: '🍇' },
    { name: 'mango', icon: '🥭' },
    { name: 'kiwi', icon: '🥝' },
    { name: 'grapes', icon: '🍇' },
    { name: 'watermelon', icon: '🍉' },
    { name: 'peach', icon: '🍑' },
    { name: 'pear', icon: '🍐' },
    { name: 'plum', icon: '🍑' },
    { name: 'cherries', icon: '🍒' },
    { name: 'figs', icon: '🍇' },
  ],
  Carbs: [
    { name: 'white rice', icon: '🍚' },
    { name: 'brown rice', icon: '🍘' },
    { name: 'noodles', icon: '🍜' },
    { name: 'pasta', icon: '🍝' },
    { name: 'potato', icon: '🥔' },
    { name: 'sweet potato', icon: '🍠' },
    { name: 'white bread', icon: '🍞' },
    { name: 'wholemeal bread', icon: '🍞' },
    { name: 'wraps', icon: '🌯' },
    { name: 'bread rolls', icon: '🍞' },
    { name: 'quinoa', icon: '🥣' },
    { name: 'couscous', icon: '🥘' },
    { name: 'oats', icon: '🥣' },
    { name: 'crackers', icon: '🍘' },
    { name: 'baguette', icon: '🥖' },
    { name: 'crumpets', icon: '🍞' },
    { name: 'scones', icon: '🍪' },
  ],
  Extras: [
    { name: 'cheddar cheese', icon: '🧀' },
    { name: 'feta cheese', icon: '🧀' },
    { name: 'yoghurt', icon: '🥛' },
    { name: 'double cream', icon: '🍶' },
    { name: 'butter', icon: '🧈' },
    { name: 'baked beans', icon: '🫘' },
    { name: 'kidney beans', icon: '🫘' },
    { name: 'chickpeas', icon: '🥫' },
    { name: 'lentils', icon: '🍲' },
    { name: 'peanuts', icon: '🥜' },
    { name: 'sunflower seeds', icon: '🌻' },
    { name: 'avocado', icon: '🥑' },
    { name: 'green olives', icon: '🫒' },
    { name: 'black olives', icon: '🫒' },
    { name: 'gherkins', icon: '🥒' },
    { name: 'clotted cream', icon: '🍶' },
    { name: 'apple cider vinegar', icon: '🍏' },
    { name: 'marmite', icon: '🍞' },
    { name: 'mustard', icon: '🍯' },
    { name: 'worcestershire sauce', icon: '🍯' },
    { name: 'tomato ketchup', icon: '🍅' },
  ],
  HerbsAndSpices: [
    { name: 'basil', icon: '🌿' },
    { name: 'oregano', icon: '🌿' },
    { name: 'parsley', icon: '🌿' },
    { name: 'rosemary', icon: '🌿' },
    { name: 'thyme', icon: '🌿' },
    { name: 'mint', icon: '🌱' },
    { name: 'coriander', icon: '🌿' },
    { name: 'paprika', icon: '🧂' },
    { name: 'cayenne pepper', icon: '🌶️' },
    { name: 'garam masala', icon: '🍛' },
    { name: 'cinnamon', icon: '🍩' },
    { name: 'cloves', icon: '🧄' },
  ],
};

export const cuisineCategories = {
  Asian: [
    { name: 'chinese', icon: '🥢' },
    { name: 'japanese', icon: '🍱' },
    { name: 'thai', icon: '🍜' },
    { name: 'indian', icon: '🍛' },
    { name: 'korean', icon: '🍲' },
    { name: 'vietnamese', icon: '🥢' },
  ],
  European: [
    { name: 'italian', icon: '🍝' },
    { name: 'french', icon: '🥖' },
    { name: 'greek', icon: '🥙' },
    { name: 'spanish', icon: '🥘' },
    { name: 'turkish', icon: '🥙' },
    { name: 'english', icon: '🍴' },
    { name: 'german', icon: '🥨' },
  ],
  American: [
    { name: 'american', icon: '🍔' },
    { name: 'mexican', icon: '🌮' },
    { name: 'bbq', icon: '🍖' },
    { name: 'brazilian', icon: '🥩' },
    { name: 'caribbean', icon: '🇯🇲' },
    { name: 'cuban', icon: '🇨🇺' },
    { name: 'southern', icon: '🍖' },
    { name: 'tex-mex', icon: '🌮' },
  ],
  Other: [
    { name: 'mediterranean', icon: '🫒' },
    { name: 'middle-eastern', icon: '🧆' },
    { name: 'african', icon: '🥘' },
    { name: 'fusion', icon: '🍽️' },
  ],
};
