import React from 'react';
import getPosts from '@/app/actions/getPosts';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import SocialShare from '@/components/SocialShare';

// Generate dynamic metadata based on recipe data
export async function generateMetadata({ params }) {
  const { post } = params;

  try {
    const postData = await getPosts(post);

    return {
      title: `${postData.title} | SmartRecipe AI`,
      description: postData.description.replace(/<[^>]*>/g, '').slice(0, 160),
      openGraph: {
        title: postData.title,
        description: postData.description.replace(/<[^>]*>/g, '').slice(0, 160),
        type: 'article',
        url: `https://smartrecipeai.com/blog/${post}`,
      },

      // Add JSON-LD Schema
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'Recipe',
        name: postData.title,
        description: postData.description.replace(/<[^>]*>/g, ''),
        cookTime: postData.cookTime,
        recipeYield: postData.servings,
        recipeIngredient: [], // You would populate this from your data
        author: {
          '@type': 'Person',
          name: 'SmartRecipe Ai', // Update with actual author
        },
      },
    };
  } catch (error) {
    console.error('Error generating metadata:', error);
    // Return default metadata if we can't fetch the recipe
    return {
      title: 'Blog | SmartRecipe Ai',
      description:
        'Discover delicious recipes and cooking inspiration at SmartRecipe Ai',
    };
  }
}

export const revalidate = 86400;

const PostPage = async ({ params }) => {
  const { post } = params;

  try {
    const postData = await getPosts(post);

    return (
      <>
        <article>
          <header className='bg-primary text-center py-32'>
            <div className='max-w-5xl mx-auto'>
              <h1 className='text-5xl font-bold text-white px-4 py-8 rounded-lg uppercase'>
                {postData.title}
              </h1>
              <div
                className='rich-text-content text-white px-4'
                dangerouslySetInnerHTML={{ __html: postData.description }}
              />
            </div>
          </header>

          <div className='container mx-auto px-4 py-8'>
            <section className='recipe-details flex flex-row gap-4'>
              {postData.difficulty && (
                <p className='bg-primary/10 text-primary rounded-lg p-2'>
                  {postData.difficulty}
                </p>
              )}
              {postData.cookTime && (
                <p className='bg-primary/10 text-primary rounded-lg p-2'>
                  {postData.cookTime}
                </p>
              )}
              {postData.servings && (
                <p className='bg-primary/10 text-primary rounded-lg p-2'>
                  <span className=''>Servings</span> {postData.servings}
                </p>
              )}
            </section>

            <section
              className='recipe-instructions rich-text-content max-w-5xl mt-8'
              dangerouslySetInnerHTML={{ __html: postData.copy }}
            />
            <p className='text-sm text-gray-500 mt-8 italic'>
              We cannot take responsibility for poorly cooked or unappetising
              recipes. These recipes are generated by AI and have therefore not
              been tested in the real world.
            </p>
          </div>
          <SocialShare shareUrl={`https://smartrecipeai.com/blog/${post}`} />
        </article>
        <div className='bg-primary/60 py-12 mt-12 rounded-lg text-white'>
          <div className='text-center'>
            <h2 className='text-2xl font-bold mb-4'>
              Want to Create Your Own Recipe?
            </h2>
            <p className='text-white mb-6 max-w-xl mx-auto'>
              Try our AI-powered recipe generator to create unique dishes
              tailored to your preferences.
            </p>
            <Link
              href='/recipe-generator'
              className='btn bg-white hover:bg-white/90 normal-case px-8 min-w-[200px]'
            >
              Generate a Recipe →
            </Link>
          </div>
        </div>
      </>
    );
  } catch (error) {
    console.error('Error fetching post:', error);
    // If post not found or error occurs, show 404 page
    notFound();
  }
};

export default PostPage;
