import React from 'react';
import getPosts from '@/app/actions/getPosts';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import SocialShare from '@/components/SocialShare';
import Image from 'next/image';

export async function generateMetadata({ params }) {
  const { post } = await params;

  try {
    const postData = await getPosts(post);

    return {
      title: `${postData.title} | Smart Recipe AI`,
      description: postData.description.replace(/<[^>]*>/g, '').slice(0, 160),
      openGraph: {
        title: postData.title,
        description: postData.description.replace(/<[^>]*>/g, '').slice(0, 160),
        type: 'article',
        url: `https://smartRecipe AI.com/blog/${post}`,
      },

      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'Recipe',
        name: postData.title,
        description: postData.description.replace(/<[^>]*>/g, ''),
        cookTime: postData.cookTime,
        recipeYield: postData.servings,
        recipeIngredient: [], // You would populate this from your data
        author: {
          '@type': 'Person',
          name: 'Smart Recipe AI', // Update with actual author
        },
      },
    };
  } catch (error) {
    console.error('Error generating metadata:', error);
    // Return default metadata if we can't fetch the recipe
    return {
      title: 'Blog | Smart Recipe AI',
      description:
        'Discover delicious recipes and cooking inspiration at Smart Recipe AI',
    };
  }
}

export const revalidate = 86400;

const PostPage = async ({ params }) => {
  const { post } = await params;

  try {
    const postData = await getPosts(post);

    return (
      <>
        <article>
          <header className='bg-gradient-to-br from-primary to-primary/80 text-center py-32 relative overflow-hidden'>
            {/* Background AI Robot Logo - Right Side */}
            <div className='absolute top-1/2 right-8 md:right-16 transform -translate-y-1/2 opacity-10'>
              <Image
                src='/ai-robot.png'
                alt='Smart Recipe AI Logo'
                width={600}
                height={600}
                className='w-[350px] h-[350px] md:w-[500px] md:h-[500px] lg:w-[600px] lg:h-[600px] object-contain'
                priority
              />
            </div>

            <div className='max-w-3xl mx-auto relative z-10'>
              <h1 className='text-5xl font-bold px-4 py-8 rounded-lg uppercase'>
                {postData.title}
              </h1>
              <div
                className='rich-text-content px-4'
                dangerouslySetInnerHTML={{ __html: postData.description }}
              />
            </div>
          </header>

          <div className='container mx-auto px-4 py-8'>
            <section className='recipe-details flex flex-row gap-4'>
              {postData.difficulty && (
                <p className='bg-primary/10 text-primary rounded-lg p-2'>
                  {postData.difficulty}
                </p>
              )}
              {postData.cookTime && (
                <p className='bg-primary/10 text-primary rounded-lg p-2'>
                  {postData.cookTime}
                </p>
              )}
              {postData.servings && (
                <p className='bg-primary/10 text-primary rounded-lg p-2'>
                  <span className=''>Servings</span> {postData.servings}
                </p>
              )}
            </section>

            <section
              className='recipe-instructions rich-text-content max-w-5xl mt-8'
              dangerouslySetInnerHTML={{ __html: postData.copy }}
            />
            <p className='text-sm text-gray-500 mt-8 italic'>
              We cannot take responsibility for poorly cooked or unappetising
              recipes. These recipes are generated by AI and have therefore not
              been tested in the real world.
            </p>
          </div>
          <SocialShare shareUrl={`https://smartRecipe AI.com/blog/${post}`} />
        </article>
        <div className='bg-primary py-12 mt-12 rounded-lg relative overflow-hidden'>
          {/* Background AI Robot Logo for CTA */}
          <div className='absolute bottom-4 left-8 opacity-5 pointer-events-none hidden md:block'>
            <Image
              src='/ai-robot.png'
              alt='Smart Recipe AI Logo'
              width={200}
              height={200}
              className='w-[200px] h-[200px] object-contain'
            />
          </div>

          <div className='text-center relative z-10'>
            <h2 className='text-2xl font-bold mb-4'>
              Want to Create Your Own Recipe?
            </h2>
            <p className='mb-6 max-w-xl mx-auto'>
              Try our AI-powered recipe generator to create unique dishes
              tailored to your preferences.
            </p>
            <Link
              href='/recipe-generator'
              className='btn bg-secondary hover:bg-secondary/40 border border-secondary normal-case px-8 min-w-[200px]'
            >
              Generate a Recipe →
            </Link>
          </div>
        </div>
      </>
    );
  } catch (error) {
    console.error('Error fetching post:', error);
    // If post not found or error occurs, show 404 page
    notFound();
  }
};

export default PostPage;
